# Generated by Django 4.1.4 on 2022-12-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employees",
            new_name="Employee",
        ),
    ]
