# Generated by Django 4.1.3 on 2022-12-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0002_comments_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="signature",
            field=models.CharField(default="hello", max_length=100),
        ),
    ]
