# Generated by Django 4.1.3 on 2022-12-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0003_comments_signature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="comments",
            new_name="Comment",
        ),
    ]
