# Generated by Django 4.1.4 on 2022-12-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="zip_code",
            field=models.CharField(max_length=5),
        ),
    ]
